### ISSUE TITLE
Too many shops when the server starts crashes paper

### ISSUE THREAD

**Issue by jere62smi** [EpicEricEE/ShopChest#296] opened 2020-01-12 10:26 UTC
Hello,
Having many shops on my server, when launching the server, the shops seem to want to load all at once or the method is not good for servers with many shops to load, it would require loads per package of 100 for example. Here is the error that I put paper.
This problem seems to have been present for 3 years, it might be time to fix it and resume some activity with this plugin...
http://bin.mc-imperia.fr/rEmY84zaet

**Comment by EpicEricEE** [comment] 2020-01-19 16:02
The problem is that the plugin loads all shops on server start, which includes checking whether there is a chest and space above the chest. For that check to be done, the chunk where the shop is in has to be loaded. When there are a lot of shops spread across the world, many chunks are being loaded at once which probably crashes the server.

I would have to make quite a few changes to improve this, that I currently do not have enough time for.

**Comment by jere62smi** [comment] 2020-01-19 20:08
Hmm I see, if I ever manage to make this modification, tested and approved, would you be interested in officially putting it in the plugin?

**Comment by EpicEricEE** [comment] 2020-02-20 12:32
Should be fixed with [build 83](https://ci.codemc.io/job/EpicEricEE/job/ShopChest/). Leave a message if that is not the case.

**Comment by jere62smi** [comment] 2020-02-20 19:19
Hello,
I tested and got this error, it doesn't seem to work but may still seem to load faster.
http://bin.mc-imperia.fr/Nno9uJvEAj

**Comment by EpicEricEE** [comment] 2020-02-20 20:16
Can you try this version below? I could think of one more potential fix
[ShopChest-1.13-SNAPSHOT.zip](https://github.com/EpicEricEE/ShopChest/files/4232809/ShopChest-1.13-SNAPSHOT.zip)

**Comment by jere62smi** [comment] 2020-02-21 16:17
Good news, I no longer had any crash paper messages, I had more than 3600 shops to load and it seems to have worked without bringing any lags! Thank you for this optimization.

**Comment by EpicEricEE** [comment] 2020-02-21 17:24
Awesome, closing with 26025ef

**Closed by EpicEricEE** 2020-02-21 17:24 UTC
