### ISSUE TITLE
1.14 Version?

### ISSUE THREAD

**Issue by Blueeyestar** [EpicEricEE/ShopChest#253] opened 2019-04-27 12:37 UTC
How do you do?
will there be a 1.14 version of ShopChest? That would be really great if there would be an answer. So far my server has appreciated this plugin very much.

**Comment by EpicEricEE** [comment] 2019-04-28 21:29
I have added 1.14 support to the latest snapshot. You can try it, however, it probably contains some issues (but also some fixes 😄 )

Closing with 77a837f

**Closed by EpicEricEE** 2019-04-28 21:29 UTC

**Comment by Blueeyestar** [comment] 2019-04-28 22:24
i have vault on it but there are still problems in the console with the file

[00:20:37] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[00:20:37] [Server thread/ERROR]: [ShopChest] Could not find any Vault economy dependency!
[00:20:37] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
[00:20:37] [Server thread/ERROR]: Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:216) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:370) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:150) [ShopChest-1.13-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by EpicEricEE** [comment] 2019-04-29 08:44
You need an economy plugin that hooks into Vault. Vault is only the bridge
between this plugin and the economy plugin.

Blueeyestar <notifications@github.com> schrieb am Mo., 29. Apr. 2019, 00:24:

**Comment by Blueeyestar** [comment] 2019-04-29 15:14
unfortunately it still doesn't work :( 

enclosed the error code


https://pastebin.com/RQeFKqiN

**Comment by EpicEricEE** [comment] 2019-04-29 16:04
Which WorldGuard version are you using?

**Comment by Blueeyestar** [comment] 2019-04-29 16:18
we have never used worldguard before. we always use RedProtec. so shopchest worked very well for the last 1 1/2 years

**Comment by EpicEricEE** [comment] 2019-04-29 16:34
Ok, I think I've found the issue. I'll let you know when it's fixed.

**Comment by Blueeyestar** [comment] 2019-04-29 16:47
That's great. Thank you :)  Is it mega good plugin it should continue to make many users happy :)

**Comment by EpicEricEE** [comment] 2019-04-29 19:11
Done, please have a try.

**Comment by Blueeyestar** [comment] 2019-04-29 19:17
Okay, I'll do it and then let you know.

**Comment by Blueeyestar** [comment] 2019-04-29 19:29
A shop will be created in first view. But fast one notices it is none. Only the item hovers above the box. you cannot buy anything and no price is displayed. if you delete the shop, the item still hovers above the box and can no longer be removed.

![2019-04-29_21 26 08](https://user-images.githubusercontent.com/35557302/56921329-d23faa00-6ac5-11e9-8c47-1f6bda75885f.png)

**Comment by Blueeyestar** [comment] 2019-05-05 13:46
No more idea how to solve the problem or will the plugin be abandoned now?

**Comment by EpicEricEE** [comment] 2019-05-05 14:46
Well, I don't know how to reproduce this. It works for me. Do you get any other error messages?

For the other problem, your language file is missing the new entries, so you have to either add them manually or delete the file to let the plugin recreate a new one.

**Comment by Blueeyestar** [comment] 2019-05-05 15:02
You're right, it works if I regenerate the file :) can you deactivate the message that my login is always available that an update is available?

**Comment by EpicEricEE** [comment] 2019-05-05 15:06
Disable `enable-update-checker` in the config. You may have to regenerate that file as well (or add the property manually).

**Comment by Blueeyestar** [comment] 2019-05-05 15:12
**Do I have to add that??** 


shop-limits:

  # Set whether admin shops should be excluded of the shop limits.
  # If set to true, admin shops won't be added to a player's shop count.
  exclude-admin-shops: true

  # Set the amount of shops that anyone who doesn't have a
  # specific permission may have.
  # If you don't want the players to have a limit by default
  # set the value to -1.
  default: 0
  
enable-update-checker: false

**Comment by EpicEricEE** [comment] 2019-05-05 15:14
Yes, but there have to be no spaces in front of it (unlike the properties above). You could also put it at the beginning, but that doesn't matter.

**Comment by Blueeyestar** [comment] 2019-05-05 15:59
I have done it now so and restarted it but it still comes...  unfortunately

blacklist:
# - "STONE:1"
# - "DIAMOND_BLOCK"

enable-update-checker:false

# Set the events of AreaShop when shops on that region should be removed.
# Important: You must have exactly 2 leading spaces in each line
# Valid values are: DELETE, UNRENT, RESELL, SELL
areashop-remove-shops:
  - "DELETE"
  - "UNRENT"
  - "RESELL"
  - "SELL"

**Comment by Blueeyestar** [comment] 2019-05-05 16:01
[17:57:14] [Server thread/ERROR]: Cannot load plugins/ShopChest/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 195, column 1:
    enable-update-checker:false
    ^
could not find expected ':'
 in 'string', line 197, column 1:
    # Set the events of AreaShop whe ... 
    ^

**Comment by EpicEricEE** [comment] 2019-05-05 16:11
Can you please try to format your post properly, so I can see if you indented it correctly? Do it like this:

`\``
Put your config stuff here
\```

**Comment by Blueeyestar** [comment] 2019-05-05 16:15
https://pastebin.com/eAwzdFuv

**Comment by Blueeyestar** [comment] 2019-05-05 16:18
It worked now. I really thank you.  I am glad to be able to offer our users shops again thanks to your plugins.
