### ISSUE TITLE
The Shop Wont Work With ASkyBlock

### ISSUE THREAD

**Issue by Kinert** [EpicEricEE/ShopChest#174] opened 2017-12-28 09:54 UTC
I cant sell or buy it says (Island Is protected)

**Comment by Arrowheads844** [comment] 2018-03-26 02:22
disable "Askyblock integration" in the config file

**Comment by EpicEricEE** [comment] 2019-06-03 15:10
That should not prevent buying or selling though, since . Closing since the issue is probably no longer relevant.

**Closed by EpicEricEE** 2019-06-03 15:10 UTC
