### ISSUE TITLE
TPS issues

### ISSUE THREAD

**Issue by sigmaroot** [EpicEricEE/ShopChest#39] opened 2016-12-07 09:04 UTC
Hello!

After updating from 1.10.4 to 1.11.1, our server has performance problems. It was the only pluging that was updated, so it may cause this. The HologramUpdateListener() is using 28 % of the whole TPS performance. Actually, we have 3000+ shops on our server.

Is there something that has changed to an even higher calculation time?
Is there something that can be done (on my side) to run this stable again?

That's my config actually:

http://pastebin.com/8XdMFXxE

**Comment by gonzalociocca** [comment] 2016-12-08 07:21
me too but on 1.8.8, benchmarked with visualvm, shopchest uses a very inefficient way of updating the holograms.

**Comment by gonzalociocca** [comment] 2016-12-08 07:37
i have found the cause of the lag, or at least most of it, and fixed it, hope that the fix can be accepted by the creator of the plugin.
https://github.com/EpicEricEE/ShopChest/pull/40

**Comment by sigmaroot** [comment] 2016-12-08 08:17
Yea! Thanks a lot, that sounds logical. Did you verified it in an own build?
It would be very nice when this is increasing the performance!

**Comment by EpicEricEE** [comment] 2016-12-08 19:13
If @gonzalociocca is right, this _(or a part of this)_ should be fixed with 253e40e 👌

**Comment by sigmaroot** [comment] 2016-12-08 19:22
I've tried his solution in an own dev build but it does not change the performance 😢 
Total 14.81% (45.867s of 309.801s tick time)

**Comment by sigmaroot** [comment] 2016-12-08 19:40
https://timings.aikar.co/v2/?id=ec9af4e151eb42a0883d8f0998211e96

**Comment by EpicEricEE** [comment] 2016-12-08 19:43
Hm, there must be something in the HologramUpdateListener that is not present in the ShopItemListener as it's not using that much CPU. Unfortunately, I don't have time for this for the next 2 weeks (or more), so if anyone wants to look into improving the update method, feel free to do so.

**Comment by sigmaroot** [comment] 2016-12-09 17:30
That's very sad, because this issue is slowing down our whole server...
I hope you could get back to it asap an found a solution for it... :cry:

**Comment by gonzalociocca** [comment] 2016-12-10 15:45
Methods Generating Lag on my Server:
HologramUpdateListener.onPlayerMove.$updateHolograms().$getBlock() (4130ms)
de.epiceric.shopchest.utils.ShopUtils.getShops()(828ms)
de.epiceric.shopchest.shop.ShopItem.isVisible()(2323ms)

also getWorld().equals(anotherWorld) was causing most of the lag on my server.

**Comment by sigmaroot** [comment] 2016-12-10 16:03
Thanks @gonzalociocca for your help!

**Comment by gonzalociocca** [comment] 2016-12-13 09:33
Well, i dont have time to commit the files to this branch, because i havent used git.
alternative repo with lag fixes: https://github.com/gonzalociocca/ShopChest

**Comment by sigmaroot** [comment] 2016-12-17 19:59
Thanks, I'll give that repo a try within the next 2 weeks. I'm a bit busy atm, but will have some free time at the end of the year.

I'm going to report the results to this issue.

**Comment by sigmaroot** [comment] 2016-12-28 14:54
YES! Thank you sooooo much.
This was an awesome idea to reduce the update frequency of the update listeners!

Lag is gone, it takes now ~ 1 sec. to show the holograms on the shops but that is ok, players can wait :)

Thank you very much for your help!

@EpicEricEE 
You should include this new fastRunnable updater from @gonzalociocca 
You could:

1. Make it configurable (_enableSlowerUpdater: true_) or
2. Overwrite your updater or
3. Optimize your updater

**Closed** 2017-01-04 16:55 UTC
