### ISSUE TITLE
MySQL error when stopping server

### ISSUE THREAD

**Issue by Noiknez** [EpicEricEE/ShopChest#16] opened 2016-08-09 20:22 UTC
Hi, when i shutdown the server i get a mysql error with ShopChest :
http://pastebin.com/kVfS6JLg
It is my configuration or i dont know because a startup chestshop connect properly to the MySQL database:

> [22:21:24] [INFO] [ShopChest] Enabling ShopChest v1.9.1
[22:21:24] [INFO] [ShopChest] Using locale "en_US"
[22:21:24] [INFO] [ShopChest] Using MySQL
[22:21:25] [INFO] [ShopChest] Initialized 12 Shops

**Comment by EpicEricEE** [comment] 2016-08-09 20:25
Can you enable _enable-debug-log_ in your configuration and send me your _debug.txt_, please?

**Comment by Noiknez** [comment] 2016-08-09 20:41
It not showing any error this time.. i will get back to you soon because it happen sometimes, i will keep this option to enabled

**Comment by Noiknez** [comment] 2016-08-10 02:12
I got the error this time, my debug.txt (without sql password) I give it here because i just have 12 admin shop for the moment :
http://pastebin.com/pfCAttiy
Also is it normal the db file in /plugins/ShopChest/ ? [](http://prntscr.com/c3s5qu)
Thanks for your help !

**Comment by EpicEricEE** [comment] 2016-08-10 08:22
Ok, I'm gonna send you a custom jar-file later which might work...
With the db-file, what do you mean is (not) normal?

**Comment by Noiknez** [comment] 2016-08-10 09:54
Ok this is great!
I mean if it is normal that i have a DB file in my shopchest folder when i am connected to an external sql database

**Comment by EpicEricEE** [comment] 2016-08-10 09:57
If you once used SQLite, the file will be created. If you switch to MySQL, it won't be removed, so you have like a backup if the MySQL didn't work. However, the file won't be updated as long as you're using MySQL, so if you want, you can delete it.

**Comment by EpicEricEE** [comment] 2016-08-10 11:34
Please try [this version](https://drive.google.com/open?id=0BxqKmdgOnShjdG53Y2cwMFoxLTg). You probably won't get any stacktraces in the console, but if you get an error message in the console, you can find the stacktrace in the _debug.txt_ file _(if debug log is enabled)_. So if you get an error message in the console, please send me the _debug.txt_ file again :+1:

**Comment by Noiknez** [comment] 2016-08-10 12:43
Thank you for explaining how it work :+1: 
No error in the console or debug.txt
I just get one additional message on startup :

> [14:31:43] [INFO] [ShopChest] Enabling ShopChest v1.9.1
[14:31:43] [INFO] [ShopChest] Using locale "en_US"
[14:31:43] [INFO] [ShopChest] Could not find translation for "message.shopInfo.extended" in selected language file. Using default translation ((Extended))
[14:31:43] [INFO] [ShopChest] Using MySQL
[14:31:44] [INFO] [ShopChest] Initialized 12 Shops

Run smoothly now, i will keep you in touch if i have error in the next 2 days, thanks again !

**Comment by EpicEricEE** [comment] 2016-08-10 12:48
Perfect, the extra message is because you're missing the translation for a new message. You'll read more in the changelog when the version will be officialy published. :v: 
If you think, the issue is fixed, you can close this.

**Closed** 2016-08-10 21:29 UTC
